USE mumsched;
LOCK TABLES `course` WRITE;
/*!40000 ALTER TABLE `course` DISABLE KEYS */;
INSERT INTO `course` VALUES (1,25,'FPP',400,'Fundamental Programming Practices');
INSERT INTO `course` VALUES (2,25,'MPP',400,'Modern Programming Practices');
INSERT INTO `course` VALUES (3,25,'APL',500,'Advanced Programming Languages');
INSERT INTO `course` VALUES (4,25,'ASD',500,'Advanced Software Development');
INSERT INTO `course` VALUES (5,25,'ALG',400,'Algorithms');
INSERT INTO `course` VALUES (6,25,'BGD',500,'Big Data');
INSERT INTO `course` VALUES (7,25,'BGD-A',400,'Big Data Analytics');
INSERT INTO `course` VALUES (8,25,'BGD-T',500,'Big Data Technology');
INSERT INTO `course` VALUES (9,25,'CGR',400,'Computer Graphics');
INSERT INTO `course` VALUES (10,25,'CNS',400,'Computer Networks');
INSERT INTO `course` VALUES (11,25,'CST',400,'Computer Security');
INSERT INTO `course` VALUES (12,25,'DBMS',400,'Database Management Systems');
INSERT INTO `course` VALUES (13,25,'EA',500,'Enterprise Architecture');
INSERT INTO `course` VALUES (14,25,'ML',500,'Machine Learning');
INSERT INTO `course` VALUES (15,25,'MDP',400,'Mobile Device Programming');
INSERT INTO `course` VALUES (16,25,'MWA',500,'Modern Web Applications');
INSERT INTO `course` VALUES (17,25,'OS',400,'Operating Systems');
INSERT INTO `course` VALUES (18,25,'PP',400,'Parallel Programming');
INSERT INTO `course` VALUES (19,25,'SE',400,'Software Engineering');
INSERT INTO `course` VALUES (20,25,'WAA',500,'Web Application Architecture and Frameworks');
INSERT INTO `course` VALUES (21,25,'WAP',400,'Web Application Programming');
/*!40000 ALTER TABLE `course` ENABLE KEYS */;
UNLOCK TABLES;